### ISSUE TITLE
skidded my BSOD troll smh

### ISSUE THREAD

**Issue by xgraza** [HausemasterIssue/The-Trolls#2]
smh

**Comment by notperry1234567890** [comment]
LOL

**Comment by ghost** [comment]
lmao

**Comment by HausemasterIssue** [comment]
lol, it's just one system command.

**Comment by xgraza** [comment]
I betchu you'd never would've thought of it unless i made it lol

**Comment by HausemasterIssue** [comment]
i got the idea from u but i didnt paste anything, read the readme,

**Comment by HausemasterIssue** [comment]
all credits have been given now enjoy
