### ISSUE TITLE
ur kidding right

### ISSUE THREAD

**Issue by notperry1234567890** [HausemasterIssue/The-Trolls#5]
"just because it dosen't much your code style dosen't mean it's awful."

I don't think u know what the difference from code style to actual good code is... U use to be a cool skid until u started to take other ppl's code without credit and act like u made them oh well tho

**Comment by HausemasterIssue** [comment]
added

**Comment by HausemasterIssue** [comment]
also whyd u put ur name as the author? i mean yes u cleaned it up but i wrote the original code, well with help from stackoverflow and sxmurai of course, you could've just put @author: hausemasterissue, perry, sxmurai
